version: '3.8'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=root
      - MARIADB_DATABASE=bigfood

  web:
    image: docker.io/bitnami/laravel:9
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_DATABASE=bigfood
    volumes:
      - './:/app'
    depends_on:
      - mariadb
    ports:
      - '8000:8000'
